spring:
  application:
    name: Best Friends API
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    converters:
      preferred-json-mapper: gson

logging:
  level:
    root: WARN
    org:
      bestfriends: DEBUG
