spring:
  application:
    name: Best Friends API
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    root: WARN
    org:
      bestfriends: DEBUG
