spring:
  application:
    name: Best Friends API
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: WARN
    org:
      bestfriends: DEBUG