CREATE TABLE si_game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    played_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    num_players INT NOT NULL,
    adversary_level_id BIGINT REFERENCES si_adversary_level(id),
    result VARCHAR(10) NOT NULL,
    loss_reason VARCHAR(30),
    victory_terror_level INT,
    num_rounds INT,
    board_setup VARCHAR(50),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE si_game_spirit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES si_game(id) ON DELETE CASCADE,
    spirit_id BIGINT NOT NULL REFERENCES si_spirit(id),
    player_name VARCHAR(255) NOT NULL,
    damage_dealt INT,
    damage_prevented INT,
    fear_generated INT,
    cities_destroyed INT,
    towns_destroyed INT,
    explorers_destroyed INT,
    dahan_saved INT,
    blight_removed INT,
    notes TEXT,
    UNIQUE(game_id, spirit_id)
);

CREATE TABLE si_game_power_used (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_spirit_id BIGINT NOT NULL REFERENCES si_game_spirit(id) ON DELETE CASCADE,
    power_card_id BIGINT NOT NULL REFERENCES si_power_card(id),
    times_played INT NOT NULL DEFAULT 1
);
