CREATE TABLE si_spirit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    complexity VARCHAR(20) NOT NULL,
    description TEXT,
    primary_elements VARCHAR(255)
);

CREATE TABLE si_adversary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE si_adversary_level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adversary_id BIGINT NOT NULL REFERENCES si_adversary(id),
    level INT NOT NULL,
    difficulty INT NOT NULL,
    name VARCHAR(255),
    effect TEXT,
    UNIQUE(adversary_id, level)
);

CREATE TABLE si_power_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    card_type VARCHAR(20) NOT NULL,
    cost INT NOT NULL,
    speed VARCHAR(10) NOT NULL,
    elements VARCHAR(255),
    description TEXT,
    spirit_id BIGINT REFERENCES si_spirit(id)
);
